### PR TITLE
Change the plugin name.

### PR DESCRIPTION
**Pull request by whoopdedo**
I got a question about your changes to the plugin. The name should be changed to indicate the plugin is under new ownership.

### CODE REVIEW

**Comment by gamma** [comment]
I do mot agree. The previous plugin has not been maintained any more.

**Comment by whoopdedo** [comment]
@gamma I am the original author. Please change the name.

**Comment by gamma** [comment]
I wonder, when you're back developing on the original plugin, why not publish everything under your username? I don't want to have a second imagemap plugin. It makes no sense. I sure did only some improvements with additional work by a third person to implement the editor.

It was far more important to have the source on github which you still do not link to on your original plugin page.

**Comment by whoopdedo** [comment]
I can't anticipate what problems DokuWiki may have if two forks have the same name. But if you don't intend to change it'll be up to you to deal with the conflicts. At least please be sure that my email is not used for bug reports.

**Comment by gamma** [comment]
I must admit, that I do not understand why we couldn't leave it to just one implementation of imagemap. If you do not really want to maintain it, that is no problem as we can do this right here.

Is this about ownership? I do not want to own this repository if you, as the original author, would like to go ahead with it. This repo is simply intend to publish the otherwise hard to find. Most plugins have Github repositories already, but not this one. So please understand that I'm confused as per your request. Bug reports are solely done via the issue tracker and there have not really been any requests ...

Again: I'd happily transfer the ownership. There is no need of two different plugins.

**Comment by whoopdedo** [comment]
Because my email remained in the `getInfo` function I have received bug reports for the plugin. That function should not even have remained in the plugin since the `plugin.info.txt` was added. But I had not made the changes in this fork so I was not able to properly address the issue. Users should not be confused by installing this plugin and assuming it was written by me when it was not.

**Comment by gamma** [comment]
I removed the function. You seem not to be able to answer my questions.

**Pull request closed without merging**
